# Generated by Django 2.1.1 on 2018-10-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_auto_20181006_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(default=12334),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nomeInstituicao',
            field=models.CharField(max_length=30),
        ),
    ]
