# Generated by Django 2.1.1 on 2018-10-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_auto_20181015_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nomeInstituicao',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
